version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

references:
  # This can also be stores in the environment variables page in your project settings or a context
  ruby_envs: &ruby_envs
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
  postgres_envs: &postgres_envs
    environment:
      POSTGRES_USER: circleci-demo-ruby
      POSTGRES_DB: rails_blog_test
      POSTGRES_PASSWORD: ""

executors:
  default:
    parameters:
      ruby_tag:
        description: "The `circleci/ruby` Docker image version tag."
        type: string
        default: 2.6.3-stretch-node
    docker:
      - image: circleci/ruby:<< parameters.ruby_tag >>
        <<: *ruby_envs
  ruby_tests:
    parameters:
      ruby_tag:
        description: "The `circleci/postgres` Docker image version tag."
        type: string
        default: 2.6.3-stretch-node
      postgres_tag:
        description: "The `circleci/postgres` Docker image version tag."
        type: string
        default: 9.5-alpine
    docker:
      - image: circleci/ruby:<< parameters.ruby_tag >>
        <<: *ruby_envs
      - image: circleci/postgres:<< parameters.postgres_tag >>
        <<: *postgres_envs

jobs:
  build:
    executor: default
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/load-cache:
          key: rails-demo-bundle
      - ruby/bundle-install
      - ruby/save-cache:
          key: rails-demo-bundle
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - /*
  test:
    parallelism: 3
    executor: ruby_with_postgres
    steps:
      - attach_workspace:
        at: /tmp/workspace
      # Check DB status
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup database
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build