version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

references:
  # This can also be stores in the environment variables page in your project settings or a context
  ruby_envs: &ruby_envs
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
executors:
  default:
    parameters:
      ruby_tag:
        description: "The `circleci/ruby` Docker image version tag."
        type: string
        default: 2.6.3-stretch-node
    docker:
      - image: circleci/ruby:<< parameters.ruby_tag >>
        <<: *ruby_envs
jobs:
  build:
    executor: default
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/load-cache:
          key: rails-demo-bundle
      - ruby/bundle-install
      - ruby/save-cache:
          key: rails-demo-bundle
      # restore, install and save node_packages

workflows:
  version: 2
  build_and_test:
    jobs:
      - build